name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    variables:
      PROJECT_NAME: 'WhispMe'

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test ${{ env.PROJECT_NAME }} --collect:"XPlat Code Coverage" --results-directory artifacts/test_results/ /p:CollectCoverage=true /p:Threshold=0 /p:ThresholdStat=total /p:ExcludeByFile="**/Migrations/*"

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ${{ env.PROJECT_NAME }}/artifacts/test_results/*/coverage.cobertura.xml
